version: '3'
services:
  app:
    build:
      context: .
    command: >
      sh -c "
      npx prisma generate &&
      npm run dev
      "
    image: api-aggregator
    ports: 
      - 13000:4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:admin@db/postgres?schema=accessDB"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5430:5432
